version: '3'
services:
  container1:
    image: jayramani/webapp1
    ports:
      - 5000:5000
    volumes_from:
      - container2:ro
  container2:
    image: jayramani/webapp2
    ports:
      - 5001:5001
    volumes:
      - .:/home